### ISSUE TITLE
Fix Syntax Highlighting

### ISSUE THREAD

**Issue by s2t2** [data-creative/data-creative.github.io#2]
Syntax highlighting is not working, and needs to be fixed.

![screenshot 2016-03-31 15 26 23](https://cloud.githubusercontent.com/assets/1328807/14191411/04371cf6-f755-11e5-8169-d71a7a8c2e1d.png)

![screenshot 2016-03-31 15 26 29](https://cloud.githubusercontent.com/assets/1328807/14191435/15e7c7a2-f755-11e5-99a6-c2f58ef22d45.png)

**Comment by s2t2** [comment]
This config change doesn't help:

``` yml
kramdown:
 input: GFM
 hard_wrap: false

highlighter: rouge
```
